### ISSUE TITLE
key_prefix is ignored, so nothing gets into elasticsearch

### ISSUE THREAD

**Issue by McSvenster** [LibreCat/Catmandu-Store-Elasticsearch#18]
Set a key_prefix as told in documentation. In my catmandu.yml:

```
store:
  mydb:
    package: ElasticSearch
    options:
      index_name: oai_sk
      key_prefix: sk
```

Then do a YAML import: 
`catmandu import YAML to mydb < test.yml`

The elasticsearchlog shows: 
`..."_id":"1_12345-GS"...`
and: 
`org.elasticsearch.index.mapper.MapperParsingException: Field [_id] is a metadata field and cannot be added inside a document. Use...`
