### ISSUE TITLE
Make the lowercasing of CQL index names optional?

### ISSUE THREAD

**Issue by danmichaelo** [LibreCat/Catmandu-Store-Elasticsearch#29]
Hi. I tried to define a few indices with camelcase, such as `bib.titleSeries`:

```yaml
# catmandu.yml
store:
  es_store:
    package: ElasticSearch
    options:
      client: 6_0::Direct
      bags:
        mlnb:
          type: _doc
          cql_mapping:
            indexes:
              bib.titleSeries:
                title: Series title (440, 490, 830, 840, 400$t, 410$t, 411$t)
                field:
                  - search.series
                op:
                  'any': true
                  'all': true
                  '=': true
                  'exact': true
```

But this resulted in a CQL Query syntax error from here: https://github.com/LibreCat/Catmandu-Store-Elasticsearch/blob/8ea96b84162b199953f7ef62d496484b76685dc4/lib/Catmandu/Store/ElasticSearch/CQL.pm#L116

The problem is that the index name doesn't match because it's lowercased to `bib.titleseries` at line 112. Which I guess is done to make the index name case-insensitive when searching? This requires you to only use lowercase index names in the configuration file though. Which is not always suitable, since the `cql_mapping` is also used to generate the `explain` response by Dancer-Plugin-Catmandu-SRU. And the index names in the explain response may need to be correctly cased according to some standard, like the [bib context set](https://www.loc.gov/standards/sru/cql/contextSets/bib-context-set.html).

As a workaround I commented out line 112.

I guess one solution could be to introduce a configuration parameter that makes the lowercasing optional.

Another could be to map lowercased versions of the keys in `$indexes` to the actual keys, so that the lookup is case insensitive even if the index names are not defined using all lowercase in the configuration file. I'm a novice when it comes to Perl, but I could try to make a PR for this as a learning exercise :)

Let me know what you think.
